package com.sinius15.javaparser.ast;

/**
  Created by Sinius15 on 9-2-2015.
 */
public enum KeyWord {

    ABSTRACT,CONTINUE,FOR,NEW,SWITCH,ASSERT,DEFAULT,GOTO,
    PACKAGE,SYNCHRONIZED,BOOLEAN,DO,IF,PRIVATE,THIS,BREAK,
    DOUBLE,IMPLEMENTS,PROTECTED,THROW,BYTE,ELSE,IMPORT,PUBLIC,
    THROWS,CASE,ENUM,INSTANCEOF,RETURN,TRANSIENT,CATCH,EXTENDS,
    INT,SHORT,TRY,CHAR,FINAL,INTERFACE,STATIC,VOID,CLASS,FINALLY,
    LONG,STRICTFP,VOLATILE ,CONST,FLOAT,NATIVE,SUPER,WHILE;

    public String getName(){
        return this.name().toLowerCase();
    }
}
